version: '2'
services:
  db:
    image: postgres
    volumes:
      - data:/data/db
    ports:
      - "5432:5432"
    env_file:
      - .env
  api:
    build: .
    command: python run_server.py
    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www/static
    depends_on:
      - api
  sandbox:
    restart: always
    build: ./sandbox/
    command: npm run start
    volumes:
      - /sandbox
    ports:
      - "4000"
    depends_on:
      - api
volumes:
  data:
    external:
      name: "sandbox"
