# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 17:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='title')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('text', models.TextField(blank=True, db_column='text', null=True)),
                ('created', models.DateTimeField(blank=True, db_column='created', default=datetime.datetime.now, null=True)),
                ('modified', models.DateTimeField(blank=True, db_column='modified', default=datetime.datetime.now, null=True)),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'db_table': 'markups',
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='name')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('created', models.DateTimeField(blank=True, db_column='created', default=datetime.datetime.now, null=True)),
                ('modified', models.DateTimeField(blank=True, db_column='modified', default=datetime.datetime.now, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'todos',
            },
        ),
    ]
