# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 01:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_auto_20160721_0051'), ('api', '0003_auto_20160721_0051')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='title')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('text', models.TextField(blank=True, db_column='text', null=True)),
                ('created', models.DateTimeField(blank=True, db_column='created', default=datetime.datetime.now, null=True)),
                ('modified', models.DateTimeField(blank=True, db_column='modified', default=datetime.datetime.now, null=True)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'markups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.TextField(db_column='name')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('created', models.DateTimeField(blank=True, db_column='created', default=datetime.datetime.now, null=True)),
                ('modified', models.DateTimeField(blank=True, db_column='modified', default=datetime.datetime.now, null=True)),
            ],
            options={
                'db_table': 'todos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PortfolioMessage',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='name', null=True)),
                ('email', models.TextField(blank=True, db_column='email', null=True)),
                ('phoneNumber', models.TextField(blank=True, db_column='phonenumber', null=True)),
                ('message', models.TextField(blank=True, db_column='message', null=True)),
                ('created', models.DateTimeField(blank=True, db_column='created', default=datetime.datetime.now, null=True)),
                ('modified', models.DateTimeField(blank=True, db_column='modified', default=datetime.datetime.now, null=True)),
            ],
            options={
                'db_table': 'portfoliomessages',
                'managed': True,
            },
        ),
    ]
