# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 00:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioMessage',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='name', null=True)),
                ('email', models.TextField(blank=True, db_column='email', null=True)),
                ('phoneNumber', models.TextField(blank=True, db_column='phonenumber', null=True)),
                ('message', models.TextField(blank=True, db_column='message', null=True)),
                ('created', models.DateTimeField(blank=True, db_column='created', default=datetime.datetime.now, null=True)),
                ('modified', models.DateTimeField(blank=True, db_column='modified', default=datetime.datetime.now, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'portfoliomessages',
            },
        ),
        migrations.AlterField(
            model_name='markup',
            name='user',
            field=models.ForeignKey(db_column='user', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
