# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170409_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_title',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
