# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 00:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160721_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markup',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
