# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160721_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_column='created')),
                ('modified', models.DateTimeField(db_column='edited')),
                ('title', models.TextField(db_column='title')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('content', models.TextField(blank=True, db_column='content', null=True)),
            ],
            options={
                'db_table': 'entries',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_column='created')),
                ('modified', models.DateTimeField(db_column='edited')),
                ('name', models.TextField(db_column='name')),
            ],
            options={
                'db_table': 'tags',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='api.Tag'),
        ),
    ]
