# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170410_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
